# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkDfVb4GjAq541sbkkmvZwlkDuqj4PF_
"""

# 1. Create a list of 10 elements of four different data types like int, string, complex and float.
#ANS:
list = [5, 3.5, 3+4j, "string", "complex", 8, 3.7, "float", 11+12j, "int" ]
print(list[4])

# 2. Create a list of size 5 and execute the slicing structure.
#ANS:

List_2 = [1,5,9,5.5,"execute"]
List_2[ 0: 3]

# 3. Write a program to get the sum and multiply of all the items in a given list.
#ANS:

import numpy
List_3 =  [1,5,8,9,10]
result = numpy.prod (List_3)
print("result:", result)

# 4. Find the largest and smallest number from a given list.


List_3 =[1,5,8,9,10]
print("Smallest number: ", min(List_3))
print("Largest number: ", max(List_3))

# 5. Create a new list which contains the specified numbers after removing the even numbers from a predefined list.
#ANS:

List_4 = [1,5,8,9,10,12]
List_4 = [x for x in List_4 if x%2 ==0]
print(List_4)

# 6. Create a list of elements such that it contains the squares of the first and last 5 elements between 1 and30 (both included).
#ANS:

y = list()
for i in range (1,31):
  y.append(i**2)
print(y[:5] + y[-5:])

# 7. Write a program to replace the last element in a list with another list.
# Sample input: [1,3,5,7,9,10], [2,4,6,8]
# Expected output: [1,3,5,7,9,2,4,6,8]

Sample_input = [1,3,5,7,9,10]
Sample_input2 = [2,4,6,8]
Sample_input.extend([2,4,6,8])
print(Sample_input)

# 8. Create a new dictionary by concatenating the following two dictionaries:
# Sample input: a={1:10,2:20} b={3:30,4:40}
# Expected output: {1:10,2:20,3:30,4:40}

#ANS:

a = {1:10,2:20}
b = {3:30,4:40}

a.update(b)
print(a)

# 9. Create a dictionary that contain numbers in the form(x:x*x) where x takes all the values between 1 and n(both 1 and n included).
# Sample input: n=5
# Expected output: {1:1, 2:4, 3:9, 4:16, 5:25}

#ANS:

number = int(input("Enter the value:" ))
Dict = {}

for i in range(1, number + 1):
  Dict[i] = i*i
print("New dictionary : ", Dict)

#  10. Write a program which accepts a sequence of comma-separated numbers from console and generates a list and a tuple which contains every number in the form of string.
#Sample input: 34,67,55,33,12,98
#Expected output: [‘34’,’67’,’55’,’33’,’12’,’98’] (‘34’,’67’,’55’,’33’,’12’,’98’)

#ANS:

numbers = input("Type in numbers seperated only by a comma :" )
            
numbers_split = numbers.split(',')
numbers_tuple = tuple(numbers_split)
print(numbers_split)
print(numbers_tuple)