# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17hv2bViS4OoOpcWNCHJoA_fQddsaPL-M
"""

#1. Create three variables in a single line and assign values to them in such a manner that each one of them  belongs to a different data type.



x,y,q= 0.5, 100, 'Python'
print(x)
print(y)
print(q)
type(q)

#2. Create a variable of type complex and swap it with another variable of type integer.

k= 5+4j
b=255
k,b=b,k
print(k)
print(b)

#3.Swap two numbers using a third variable and do the same task without using any third variable.

i=10
j=20
print(i)
print(j)
temp=i
i=j
j=temp
print(i)
print(j)

# swapping the values without using third variable.
i,j=j,i
print(i)
print(j)

#4. Write a program that takes input from the user and prints it using both Python 2.x and Python 3.x version.

User1= input("What is your name?")
print("Hi :", User1)

#5. Write a program to complete the task given below:
#Ask users to enter any 2 numbers in between 1-10 , add the two numbers and keep the sum in another variable called z.
#Add 30 to z and store the output in variable result and print result as the final output.

user2=int (input("Enter number between 1 to 10: "  ))
user3 =int (input("Enter number between 1 to 10: "  ))
z= user2 + user3
z= 30 + z
print(z)

#6 Write a program to check the data type of the entered values.
#HINT: Printed output should say - The data type of the input value is : int/float/string/etc

data1= eval(input("Enter the value:"))
type(data1)

#7  Create Variables using formats such as Upper CamelCase, Lower CamelCase, SnakeCase and UPPERCASE.

snake_case_variable='Snakecase'
UpperCamelCaseVariable= 15
lowerCamelCaseVariable= 5+6j
UPPERCASEVARIABLE= 8.85
print(snake_case_variable)
type (snake_case_variable)
print(UpperCamelCaseVariable)
type(UpperCamelCaseVariable)
print(lowerCamelCaseVariable)
type(lowerCamelCaseVariable)
print(UPPERCASEVARIABLE)
type(UPPERCASEVARIABLE)

#8 If one data type value is assigned to ‘a’ variable and then a different data type value is assigned to ‘a’ again. Will it change the value? If Yes then Why?

a= 45 
print(a)
type(a)


a= 8+9j
print(a)
type(a)

# Yes, it will change the value. In python we can assign values to one variable as long as they are diffrent from its current value. 
#Whenever we assign the new value to a variable, it will remove the old value and replace it with the new one.