# -*- coding: utf-8 -*-
"""Task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15SBbVnLWiefhHlC5hG1xHdhGUHRBN90C
"""

#1. Write a program in Python to allow the error of syntax to be handled using exception handling.
#HINT: Use SyntaxError
#ANS:

x= [0,'help', 8]
for i in x:
  try :
    y= 1/2:
  except SyntaxError:
   print ("There was a syntax error")

#2. Write a program in Python to allow the user to open a file by using the argv module. If the entered name is incorrect throw an exception and ask them to enter the name again.
 #Make sure to use read only mode.

#ANS.
import sys
from sys import argv

File, Filename = argv
print("Name of the file:" , File)
print("Filename: ", Filename)

while True :
  try:
    filetobeopened = open(Filename)
    filetobeopened.close()
    break
  except:
    nextattempt = input ("Yes or No")
    if (nextattemp== "Yes"):
      filetobeopened = open(Filename)
    else:
      break

#3. Write a program to handle an error if the user entered a number more than four digits it should return “The length is too short/long !!! Please provide only four digits”.
#ANS:

while True:
  try :
    a = int(input("Enter a number: " ))
    len(a) == 4
    if len(a) !=4:
      raise ValueError("This length is too short or long!!! Please provide only four digits")
    else:
      print("This is a correct length")
  break

#4. Create a login page backend to ask users to enter the username and password. Make sure to ask for a Re-Type Password and if the password is incorrect give chance to 
#enter  it again but it should not be more than 3 times.


#ANS:

Number_of_attempts = 0
Name = input("Enter your username:" )
Password = input ("Enter your password:" )
while (Number_of_attempts <=3):
  Next_password_attempt= input("Enter the password:" )
  if Password == Next_password_attempt:
    print("Correct Password")
    break
  else:
    Number_of_attempts = Number_of_attempts+1
    if (Number_of_attempts== 3):
      print("Done with yur attempts. Please try again later")
      break

# 5. Go through the link provided below to understand finally and raise concept:
https://www.programiz.com/python-programming/exception-handling

ANs:
Done

#6. Read doc.txt file using Python File handling concept and return only the even length string from the file. Consider the content of doc.txt as given below:
#Hello I am a file
#Where you need to return the data string
#Which is of even length
#Make sure you return the content in The same link as it is present.


#ANS:

d = open ('doc.txt','w' )
d.write ("Hello I am a file\n")
d.write ("Where you need to return the data string\n")
d.write ("Which is of even length\n")
d.write ("Make sure you return the content in the same link as it is present\n")
d.close()

d = open ('doc.txt')
print(d.readline())
print(d.readline())
print(d.readline())
print(d.readline())
d.close()

